<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE design [
  <!ELEMENT design (name,description,generated,cmsversion,template+,stylesheet*,file*)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT generated (#PCDATA)>
  <!ELEMENT cmsversion (#PCDATA)>
  <!ELEMENT template (tkey,tname,tdesc,tdata,ttype_originator,ttype_name)>
  <!ELEMENT tkey (#PCDATA)>
  <!ELEMENT tname (#PCDATA)>
  <!ELEMENT tdesc (#PCDATA)>
  <!ELEMENT tdata (#PCDATA)>
  <!ELEMENT ttype_originator (#PCDATA)>
  <!ELEMENT ttype_name (#PCDATA)>
  <!ELEMENT stylesheet (csskey,cssname,cssdesc,cssmediatype,cssmediaquery,cssdata)>
  <!ELEMENT csskey (#PCDATA)>
  <!ELEMENT cssname (#PCDATA)>
  <!ELEMENT cssdesc (#PCDATA)>
  <!ELEMENT cssmediatype (#PCDATA)>
  <!ELEMENT cssmediaquery (#PCDATA)>
  <!ELEMENT cssdata (#PCDATA)>
  <!ELEMENT file (fkey,fvalue,fdata?)>
  <!ELEMENT fkey (#PCDATA)>
  <!ELEMENT fvalue (#PCDATA)>
  <!ELEMENT fdata (#PCDATA)>
]>
<design>
  <name>Minimal</name>
  <description><![CDATA[TWluaW1hbCB0ZW1wbGF0ZXMgYW5kIHN0eWxlc2hlZXRz]]></description>
  <generated><![CDATA[MTUzMTI1MzIzOQ==]]></generated>
  <cmsversion><![CDATA[Mi4yLjg=]]></cmsversion>
  <template>
    <tkey>__TPL,,897f01deaaef641d67f74d30a73e5feb__</tkey>
    <tname><![CDATA[bWluaW1hbF9tZW51]]></tname>
    <tdesc><![CDATA[]]></tdesc>
    <tdata><![CDATA[eyogbWluaW1hbCBuYXZpZ2F0aW9uICp9CnsqCiAgdmFyaWFibGVzOgogIG5vZGU6IGNvbnRhaW5zIHRoZSBjdXJyZW50IG5vZGUuCiAgYWNsYXNzOiBpcyB1c2VkIHRvIGJ1aWxkIGEgc3RyaW5nIGNvbnRhaW5pbmcgY2xhc3MgbmFtZXMgZ2l2ZW4gdG8gdGhlIGEgdGFnIGlmIG9uZSBpcyB1c2VkCiAgbGljbGFzczogaXMgdXNlZCB0byBidWlsZCBhIHN0cmluZyBjb250YWluaW5nIGNsYXNzIG5hbWVzIGdpdmVuIHRvIHRoZSBsaSB0YWcuCip9CnsqIENTUyBjbGFzc2VzIHVzZWQgaW4gdGhpcyB0ZW1wbGF0ZToKLmN1cnJlbnRwYWdlIC0gVGhlIGFjdGl2ZS9jdXJyZW50IHBhZ2UKLmJ1bGxldF9zZWN0aW9uaGVhZGVyIC0gVG8gc3R5bGUgc2VjdGlvbiBoZWFkZXIKaHIuc2VwYXJhdG9yIC0gVG8gc3R5bGUgdGhlIHJ1bGVyIGZvciB0aGUgc2VwYXJhdG9yICp9Cgp7aWYgIWlzc2V0KCRkZXB0aCl9eyRkZXB0aD0wfXsvaWZ9Cgp7aWYgaXNzZXQoJG5vZGVzKX17c3RyaXB9Cjx1bD4KICB7Zm9yZWFjaCAkbm9kZXMgYXMgJG5vZGV9CiAgICB7aWYgJG5vZGUtPnR5cGUgPT0gJ3NlY3Rpb25oZWFkZXInfQogICAgICB7KiBzZWN0aW9uIGhlYWRlciAqfQogICAgICA8bGkgY2xhc3M9InNlY3Rpb25oZWFkZXJ7aWYgJG5vZGUtPnBhcmVudH0gYWN0aXZlcGFyZW50ey9pZn0iPgogICAgICAgIHskbm9kZS0+bWVudXRleHR9CiAgICAgICAge2lmIGlzc2V0KCRub2RlLT5jaGlsZHJlbil9CiAgICAgICAgICB7aW5jbHVkZSBmaWxlPSRzbWFydHkudGVtcGxhdGUgbm9kZXM9JG5vZGUtPmNoaWxkcmVuIGRlcHRoPSRkZXB0aCsxfQogICAgICAgIHsvaWZ9CiAgICAgIDwvbGk+CiAgICB7ZWxzZSBpZiAkbm9kZS0+dHlwZSA9PSAnc2VwYXJhdG9yJ30KICAgICAgPGxpIHN0eWxlPSJsaXN0LXN0eWxlLXR5cGU6IG5vbmU7Ij48aHIgY2xhc3M9InNlcGFyYXRvciIvPjwvbGk+CiAgICB7ZWxzZX0KICAgICAgeyogcmVndWxhciBpdGVtICp9CiAgICAgIHskbGljbGFzcz0nJ30KICAgICAgeyRhY2xhc3M9Jyd9CiAgICAgIHtpZiAkbm9kZS0+Y3VycmVudH0KICAgICAgICB7JGxpY2xhc3M9J2N1cnJlbnRwYWdlJ30KICAgICAgICB7JGFjbGFzcz0nY3VycmVudHBhZ2UnfQogICAgICB7ZWxzZWlmICRub2RlLT5wYXJlbnR9CiAgICAgICAgeyRsaWNsYXNzPSdhY3RpdmVwYXJlbnQnfQogICAgICAgIHskYWNsYXNzPSdhY3RpdmVwYXJlbnQnfQogICAgICB7L2lmfQogICAgICA8bGl7aWYgJGxpY2xhc3MgIT0gJyd9IGNsYXNzPSJ7JGxpY2xhc3N9InsvaWZ9PgogICAgICAgIDxhe2lmICRhY2xhc3MgIT0nJ30gY2xhc3M9InskYWNsYXNzfSJ7L2lmfSBocmVmPSJ7JG5vZGUtPnVybH0ie2lmICRub2RlLT50YXJnZXQgbmUgIiJ9IHRhcmdldD0ieyRub2RlLT50YXJnZXR9InsvaWZ9Pnskbm9kZS0+bWVudXRleHR9PC9hPgogICAgICAgIHtpZiBpc3NldCgkbm9kZS0+Y2hpbGRyZW4pfQogICAgICAgICAge2luY2x1ZGUgZmlsZT0kc21hcnR5LnRlbXBsYXRlIG5vZGVzPSRub2RlLT5jaGlsZHJlbiBkZXB0aD0kZGVwdGgrMX0KICAgICAgICB7L2lmfQogICAgICA8L2xpPgogICAgey9pZn0KICB7L2ZvcmVhY2h9CjwvdWw+Cnsvc3RyaXB9ey9pZn0=]]></tdata>
    <ttype_originator><![CDATA[TmF2aWdhdG9y]]></ttype_originator>
    <ttype_name><![CDATA[bmF2aWdhdGlvbg==]]></ttype_name>
  </template>
  <template>
    <tkey>__TPL,,30fc6bbba82125243ecf4ddb27fee645__</tkey>
    <tname><![CDATA[TWluaW1hbA==]]></tname>
    <tdesc><![CDATA[QSBTaW1wbGUsIG1pbmltYWwgcGFnZSB0ZW1wbGF0ZQ==]]></tdesc>
    <tdata><![CDATA[e3Byb2Nlc3NfcGFnZWRhdGF9CjwhRE9DVFlQRSBodG1sIFBVQkxJQyAiLS8vVzNDLy9EVEQgWEhUTUwgMS4wIFRyYW5zaXRpb25hbC8vRU4iCiJodHRwOi8vd3d3LnczLm9yZy9UUi94aHRtbDEvRFREL3hodG1sMS10cmFuc2l0aW9uYWwuZHRkIj4KCjxodG1sIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiB4bWw6bGFuZz0iZW4iIGxhbmc9ImVuIj4KeyogQ2hhbmdlIGxhbmc9ImVuIiB0byB0aGUgbGFuZ3VhZ2Ugb2YgeW91ciBzaXRlICp9Cgo8aGVhZD4KCjx0aXRsZT57c2l0ZW5hbWV9IC0ge3RpdGxlfTwvdGl0bGU+CnsqIFRoZSBzaXRlbmFtZSBpcyBjaGFuZ2VkIGluIFNpdGUgQWRtaW4vR2xvYmFsIHNldHRpbmdzLiB7dGl0bGV9IGlzIHRoZSBuYW1lIG9mIGVhY2ggcGFnZSAqfQoKe21ldGFkYXRhfQp7KiBEb25cJ3QgcmVtb3ZlIHRoaXMhIE1ldGFkYXRhIGlzIGVudGVyZWQgaW4gU2l0ZSBBZG1pbi9HbG9iYWwgc2V0dGluZ3MuICp9Cgp7Y21zX3N0eWxlc2hlZXR9CnsqIFRoaXMgaXMgaG93IGFsbCB0aGUgc3R5bGVzaGVldHMgYXR0YWNoZWQgdG8gdGhpcyB0ZW1wbGF0ZSBhcmUgbGlua2VkIHRvICp9Cgo8L2hlYWQ+Cgo8Ym9keT4KCiAgICAgIHsqIFN0YXJ0IE5hdmlnYXRpb24gKn0KICAgICAgPGRpdiBzdHlsZT0iZmxvYXQ6IGxlZnQ7IHdpZHRoOiAyNSU7Ij4KICAgICAgICAge05hdmlnYXRvciBsb2FkcHJvcHM9MCB0ZW1wbGF0ZT0nX19UUEwsLDg5N2YwMWRlYWFlZjY0MWQ2N2Y3NGQzMGE3M2U1ZmViX18nfQogICAgICA8L2Rpdj4KICAgICAgeyogRW5kIE5hdmlnYXRpb24gKn0KCiAgICAgIHsqIFN0YXJ0IENvbnRlbnQgKn0KICAgICAgPGRpdj4KICAgICAgICAgPGgyPnt0aXRsZX08L2gyPgogICAgICAgICB7Y29udGVudH0gCiAgICAgIDwvZGl2PgogICAgICB7KiBFbmQgQ29udGVudCAqfQoKPC9ib2R5Pgo8L2h0bWw+]]></tdata>
    <ttype_originator><![CDATA[X19DT1JFX18=]]></ttype_originator>
    <ttype_name><![CDATA[cGFnZQ==]]></ttype_name>
  </template>
  <stylesheet>
    <csskey>__CSS,,cb23a2168fcdd25c7406c6e8ee2e3de8__</csskey>
    <cssname><![CDATA[SGFuZGhlbGQ=]]></cssname>
    <cssdesc><![CDATA[U3R5bGVzaGVldCBmb3Igb2xkZXIgbW9iaWxlIGRldmljZXM=]]></cssdesc>
    <cssmediatype><![CDATA[aGFuZGhlbGQ=]]></cssmediatype>
    <cssmediaquery><![CDATA[]]></cssmediaquery>
    <cssdata><![CDATA[LyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKgpTYW1wbGUgc3R5bGVzaGVldCBmb3IgbW9iaWxlIGFuZCBzbWFsbCBzY3JlZW4gaGFuZGhlbGQgZGV2aWNlcwoKSnVzdCBhIHNpbXBsZSBsYXlvdXQgc3VpdGFibGUgZm9yIHNtYWxsZXIgc2NyZWVucyB3aXRoIGxlc3MgCnN0eWxpbmcgY2FiYXBpbGl0aWVzIGFuZCBtaW5pbWFsIGNzcwoKTm90ZTogSWYgeW91IGRvbnQgd2FudCB0byBzdXBwb3J0IG1vYmlsZSBkZXZpY2VzIHlvdSBjYW4Kc2FmZWx5IHJlbW92ZSB0aGlzIHN0eWxlc2hlZXQuCioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8KLyogZm9vYmFyIHJlbW92ZSBhbGwgcGFkZGluZyBhbmQgbWFyZ2lucyBhbmQgc2V0IHdpZHRoIHRvIDEwMCUuIFRoaXMgc2hvdWxkIGJlIGRlZmF1bHQgZm9yIGhhbmRoZWxkIGRldmljZXMgYnV0IGl0cyBnb29kIHRvIHNldCB0aGVzZSBleHBsaWNpdGx5ICovCmJvZHkgewptYXJnaW46MDsKcGFkZGluZzowOwp3aWR0aDoxMDAlOwp9CgovKiBoaWRlIGFjY2Vzc2liaWxpdHkgbm9wcmludCBhbmQgZGVmaW5pdGlvbiAqLwouYWNjZXNzaWJpbGl0eSwKLm5vcHJpbnQsCmRmbiB7CmRpc3BsYXk6bm9uZTsKfQoKLyogZG9udCB3YW50IHRvIGRvd25sb2FkIGltYWdlIGZvciBoZWFkZXIgc28ganVzdCBzZXQgYmcgY29sb3IgKi8KZGl2I2hlYWRlciwKZGl2I2Zvb3RlciB7CmJhY2tncm91bmQtY29sb3I6ICMzODVDNzI7ICAKY29sb3I6ICNmZmY7CnRleHQtYWxpZ246Y2VudGVyOwp9CgovKiB0ZXh0IGNvbG9ycyBmb3IgaGVhZGVyIGFuZCBmb290ZXIgKi8KZGl2I2hlYWRlciBhLApkaXYjZm9vdGVyIGEgewpjb2xvcjogI2ZmZjsKfQoKLyogdGhpcyBkb2VzbnQgbG9vayBhcyBuaWNlLCBidXQgdGFrZXMgbGVzcyBzcGFjZSAqLwpkaXYjbWVudV92ZXJ0IHVsIGxpLApkaXYjbWVudV9ob3JpeiB1bCBsaSB7CmRpc3BsYXk6aW5saW5lOwp9CgovKiBzbWFsbCBib3JkZXIgYXQgdGhlIGJvdHRvbSB0byBoYXZlIHNvbWUgaW5kaWNhdG9yICovCmRpdiNtZW51X3ZlcnQgdWwsCmRpdiNtZW51X2hvcml6IHVsIHsKYm9yZGVyLWJvdHRvbToxcHggc29saWQgI2ZmZjsKfQoKLyogc2F2ZSBzb21lIHNwYWNlICovCmRpdi5icmVhZGNydW1icyB7CmRpc3BsYXk6bm9uZTsKfQ==]]></cssdata>
  </stylesheet>
  <file>
    <fkey>__CSS,,cb23a2168fcdd25c7406c6e8ee2e3de8__</fkey>
    <fvalue>Handheld</fvalue>
  </file>
  <file>
    <fkey>__TPL,,30fc6bbba82125243ecf4ddb27fee645__</fkey>
    <fvalue>Minimal</fvalue>
  </file>
  <file>
    <fkey>__TPL,,897f01deaaef641d67f74d30a73e5feb__</fkey>
    <fvalue>minimal_menu</fvalue>
  </file>
</design>
